train: []

inference:
  - _target_: src.metrics.MelSpectrogramDistance
    name: "MelDistance"
    sample_rate: 22050
    n_fft: 1024
    hop_length: 256
    win_length: 1024
    n_mels: 80
    f_min: 0.0
    f_max: 8000.0

#  - _target_: src.metrics.STFTDistance
#    name: "STFTLoss"
#    fft_sizes: [512, 1024, 2048]
#    hop_sizes: [128, 256, 512]
#    win_sizes: [512, 1024, 2048]
#
#  - _target_: src.metrics.PESQScore
#    name: "PESQ"
#    sample_rate: 22050
#    mode: "wb"