train:
  - _target_: src.metrics.MelDistance
    name: "MelDistance"
    sample_rate: 22050
    n_fft: 1024
    hop_length: 256
    win_length: 1024
    n_mels: 80
    f_min: 0.0
    f_max: 8000.0

  - _target_: src.metrics.LSD
    name: "LSD"
    n_fft: 1024
    hop_length: 256
    win_length: 1024

inference:
  - _target_: src.metrics.MelDistance
    name: "MelDistance"
    sample_rate: 22050
    n_fft: 1024
    hop_length: 256
    win_length: 1024
    n_mels: 80
    f_min: 0.0
    f_max: 8000.0

  - _target_: src.metrics.LSD
    name: "LSD"
    n_fft: 1024
    hop_length: 256
    win_length: 1024

  - _target_: src.metrics.PESQ
    name: "PESQ"
    sample_rate: 22050

  - _target_: src.metrics.STOI
    name: "STOI"
    sample_rate: 22050
