instance_transforms:
  train:
    mel:
      _target_: src.transforms.audio_transforms.AudioToMelSpectrogram
      sample_rate: 22050
      n_fft: 1024
      hop_length: 256
      win_length: 1024
      n_mels: 80
      f_min: 0.0
      f_max: 8000.0

  inference:
    mel:
      _target_: src.transforms.audio_transforms.AudioToMelSpectrogram
      sample_rate: 22050
      n_fft: 1024
      hop_length: 256
      win_length: 1024
      n_mels: 80
      f_min: 0.0
      f_max: 8000.0

batch_transforms:
  train: {}
  inference: {}